# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QlvbBNApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QlvbBNApp

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  post_install do |installer|
    system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
  end

end
